### ISSUE TITLE
CALL subquery documentation ambiguous for ordering

### ISSUE THREAD

**Issue by ikwattro** [neo4j/docs-cypher#1040]
Hi, 

Not sure if it is the right place for documentation feedback, feel free to redirect the issue wherever it should.

I was reading the following section : https://neo4j.com/docs/cypher-manual/5/subqueries/call-subquery/#call-execution-order

The beginning of the section is a bit misleading to me : 

> The order in which subqueries are executed is not defined. If a query result depends on the order of execution of subqueries, an ORDER BY clause should precede the CALL clause.

To me, that means that two subqueries in the Cypher query might not be executed in a defined order ? However the examples themselves speak more about the ordering of the rows that are scoped into the subquery ? 

Am I right to assume there is a mismatch between the beginning of the section and the intent of the section itself ?

**Comment by JPryce-Aklundh** [comment]
Thank you @ikwattro. Yes, this was a mismatch. It has been updated to say:

"The order in which rows from the outer scope are passed into subqueries is not defined. If the results of the subquery depend on the order of these rows, use an `ORDER BY `clause before the `CALL` clause to guarantee a specific processing order for the rows."

**Comment by ikwattro** [comment]
Thanks @JPryce-Aklundh
