### ISSUE TITLE
bug/snack-bar-covers-sidenav-text

### ISSUE THREAD

**Issue by aspyridakos** [neo4j/docs-cypher#503]
Snackbar with label "Was this page helpful?" blocks bottom part of right sidenav text in [aggregating functions page](https://neo4j.com/docs/cypher-manual/current/functions/aggregating/) and does not close on page refresh or submission of response data.

![image](https://user-images.githubusercontent.com/71853151/230654026-323a8025-379c-43dd-a367-ac69e78c4ca3.png)

**Comment by aspyridakos** [comment]
**_note:_** scrolling does not change visibility of snackbar here

**Comment by JPryce-Aklundh** [comment]
Hi @aspyridakos - this issue has been fixed. Thank you for your feedback!
