### ISSUE TITLE
Update duration.doc

### ISSUE THREAD

**Issue by polecpiotr** [neo4j/docs-cypher#514]
Version: 5.5.0 instance on GraphAcademy

Hey,
I'm learning neo4j through graph academy and was learning about `duration`. In docs I found [this section about inDays](https://neo4j.com/docs/cypher-manual/current/functions/temporal/duration/#functions-duration-indays). The code however returns `Duration` in other format than specified. To get the duration in days, I had to additionally call `.days`. This is also what the transcript says in [the GraphAcademy section about working with dates](https://graphacademy.neo4j.com/courses/cypher-intermediate-queries/3-working-with-cypher-data/05-dates-and-times/)

Steps to reproduce:
1. Copy the code from documentation and execute it
2. You should receive `Duration` in other formats than days - see screenshot
![image](https://user-images.githubusercontent.com/117358542/232471236-e19085a5-8c24-4c93-80e2-1415b1998b50.png)

I encounter the same issue for `toSeconds` and `toMonths`

Possible solution:
Call `days`/`seconds`/`months` in the code snippet and update return values.

**Comment by stefano-ottolenghi** [comment]
Thanks for sharing your experience. While the page you linked is _correct_, in the sense that if you run the example you specified, you get back a `Duration` object, as the docs say and show, I agree that it's not explicit how you would manipulate that object further. There is a separate page [Temporal values -- Duration](https://neo4j.com/docs/cypher-manual/current/values-and-types/temporal/#cypher-temporal-durations), but it's not easily discoverable from the page you started from, so we're gonna improve on that.

**Comment by rsill-neo4j** [comment]
This has been addressed now, in this PR: https://github.com/neo4j/docs-cypher/pull/900
The tables for duration components have been named and we added references to these tables where it's useful to understand the shown examples better. The changes are mostly in this page: https://neo4j.com/docs/cypher-manual/current/values-and-types/temporal/#cypher-temporal-durations
