### ISSUE TITLE
"shadowning of variable not allowed", a doc bug?

### ISSUE THREAD

**Issue by complyue** [neo4j/docs-cypher#542]
I would perceive from context of this doc, that "variable shadowing" may happen, but could be undesirable when not intended. Is the "not allowed" phrasing a doc bug here?

https://github.com/neo4j/docs-cypher/blob/727287b89881ba1ab1697a619c079527209e912a/modules/ROOT/pages/syntax/expressions.adoc?plain=1#LL553C1-L553C61

**Comment by stefano-ottolenghi** [comment]
As the docs point out, shadowing is _not_ allowed in those scenarios. I have expanded the two relevant examples to clarify a bit more and to show what error you would get, and how you would address it :)
