### ISSUE TITLE
Neo.ClientError.Statement.SyntaxError

### ISSUE THREAD

**Issue by Shichuan-Hao** [neo4j/docs-cypher#721]
When I execute this statement：
`MATCH (tom:Person {name:'Tom Hanks'})--{2}(colleagues:Person)
RETURN DISTINCT colleagues.name AS name, colleagues.born AS bornIn
ORDER BY bornIn LIMIT 5` 

the result:
`Neo.ClientError.Statement.SyntaxError:Quantified path patterns are not yet supported. (line 1, column 38 (offset: 37))
"MATCH (tom:Person {name:'Tom Hanks'})--{2}(colleagues:Person)"` 

why ? 
[Document address](https://neo4j.com/docs/cypher-manual/current/introduction/cypher_tutorial/)

Neo4j Browser version: 5.11.0
Neo4j Server version: 5.3.0(enterprise)

**Comment by Shichuan-Hao** [comment]
![image](https://github.com/neo4j/docs-cypher/assets/104907109/cc78da25-5fe4-4780-a3af-2b68c29e837c)

**Comment by stefano-ottolenghi** [comment]
As the error states, your Neo4j (server) version does not support [quantified path patterns](https://neo4j.com/docs/cypher-manual/current/patterns/concepts/#quantified-path-patterns), which were introduced in version 5.9 (whereas you are running 5.3). Updating your Neo4j installation will fix the issue.
